"""IR-level "uros" splitter (working around the AVM 8 KB program-size cap).

Detected via ``class C(arc4.ARC4Contract, splitter="uros")`` + per-method
``@arc4.abimethod(chunk="...")``. The target is split into a "shell" (every heavy body stubbed:
the genesis program ``main`` is created from, and the artifact carrying the full ABI under the
original name — the only ≤8 KB program that can expose every method) + one program per chunk
(that chunk's methods real, the rest stubbed). All are grafted with the uros plumbing (guard +
setup-app state) and the per-method "preceded by setup.prepare" ``appl``-arg guard. A separately
deployed ``setup`` helper (source: ``src/_uros_lib/``, emitted automatically) holds the chunks in
boxes and, per call, swaps the owning chunk into ``main`` via an inner ``UpdateApplication``. The
method runs as a real top-level txn the caller issues to ``main`` inside a 2-txn group
``[setup.prepare, main.method]`` — so it sees the real caller/args, and the chunk code stays
on-chain (composable). The grafted guard rejects any heavy-method call not immediately preceded
by ``setup.prepare``.
"""

from __future__ import annotations

import typing
from pathlib import Path

import attrs

from puya import log
from puya.avm import AVMType
from puya.compilation_artifacts import CompilationArtifact, CompiledContract
from puya.context import CompileContext
from puya.errors import CodeError
from puya.ir import models as ir
from puya.ir._utils import deep_copy
from puya.ir.types_ import AVMBytesEncoding, IRType, SizedBytesType
from puya.program_refs import ContractReference
from puya.utils import make_path_relative_to_cwd

if typing.TYPE_CHECKING:
    from puya.awst.nodes import (
        AWST,
        Contract as AwstContract,
    )

logger = log.get_logger(__name__)

ROUTER_SHORT_NAME = "__puya_arc4_router__"

# the uros library is shipped as embedded AWST (source of truth: src/_uros_lib/, regenerated by
# `poe gen_uros_setup`): the `setup` helper (emitted as its own app) and the `infra` contract
# whose guard + setter methods are grafted onto the user's `main`.
_EMBEDDED_LIB = Path(__file__).parent / "lib.awst.json"
SETUP_CONTRACT_ID = "_uros_lib.setup.UrosSetup"
SETUP_CONTRACT_NAME = "UrosSetup"
INFRA_CONTRACT_ID = "_uros_lib.infra.UrosInfra"
# infra methods grafted into `main`; the splitter keeps exactly these real in every chunk
INFRA_METHODS = ("uros_guard", "uros_set_setup")
# template method (not grafted) whose leading `appl` arg + asserts are prepended to every split
# method, so each heavy method takes the preceding setup.prepare as an arg and verifies it
GUARD_TEMPLATE_METHOD = "uros_prepare_guard"
# class-kwarg value that selects this approach: `class C(ARC4Contract, splitter=SPLITTER_KEY)`
SPLITTER_KEY = "uros"

# ordered (chunk_name, method_names) pairs — the single representation threaded (as compile.py
# pipeline state) through detection, chunk resolution (force-merge), and the deploy manifest.
UrosChunks = tuple[tuple[str, tuple[str, ...]], ...]


# --- splitter primitives ---


def split_contract(
    contract: ir.Contract, groups: list[list[str]], *, keep_real: set[str] | None = None
) -> tuple[ir.Contract, list[ir.Contract]]:
    """Partition ``contract`` into a stubbed shell plus one chunk per group (returned in group
    order). Each group is the ARC-4 method short names that stay real in that chunk; ``keep_real``
    are names that must never be stubbed in any program (the grafted infra)."""
    keep_real = keep_real or set()
    method_names = abi_method_names(contract)
    requested = {name for group in groups for name in group}
    unknown = sorted(requested - method_names)
    if unknown:
        raise CodeError(
            f"uros splitter: unknown ARC-4 method name(s): {', '.join(unknown)}"
            f" (available: {', '.join(sorted(method_names))})"
        )
    main_shell = deep_copy(contract)
    _stub_method_bodies(main_shell, requested - keep_real)
    chunks = []
    for group in groups:
        keep = set(group)
        chunk_contract = deep_copy(contract)
        # Keep every impl real; cut dispatch for non-owned methods by stubbing their
        # routing wrappers. Per-Contract DCE then prunes the impls this chunk can't
        # reach, while impls reached by internal calls from the chunk's own methods
        # survive — so internal calls to other ABI methods Just Work, with no
        # force-merge and no reachability bookkeeping (DCE already does it).
        _stub_routing_wrappers(chunk_contract, method_names - keep - keep_real)
        chunks.append(chunk_contract)
    return main_shell, chunks


def abi_method_names(contract: ir.Contract) -> set[str]:
    return {
        sub.short_name
        for sub in contract.approval_program.all_subroutines
        if sub.is_routing_wrapper
    }


def _stub_method_bodies(contract: ir.Contract, method_names: set[str]) -> None:
    for program in contract.all_programs():
        for sub in program.all_subroutines:
            if (
                sub is program.main
                or sub.is_routing_wrapper
                or sub.short_name == ROUTER_SHORT_NAME
            ):
                continue
            if sub.short_name in method_names:
                _stub_subroutine(sub)


def _stub_routing_wrappers(contract: ir.Contract, method_names: set[str]) -> None:
    """Stub the ARC-4 routing wrappers of the given methods, cutting their dispatch to the
    (kept-real) impls. Each impl then survives per-Contract DCE only if reached by an internal
    call from a method this chunk still owns — so cross-chunk internal calls keep working while
    everything else is pruned, with no force-merge needed."""
    for program in contract.all_programs():
        for sub in program.all_subroutines:
            if sub.is_routing_wrapper and sub.short_name in method_names:
                _stub_subroutine(sub)


def _stub_subroutine(sub: ir.Subroutine) -> None:
    """Replace a subroutine body with a single block returning default values."""
    loc = sub.source_location
    results = [_default_value(ir_type, loc) for ir_type in sub.returns]
    # id must be assigned: the inliner pass asserts on BasicBlock.id
    block = ir.BasicBlock(source_location=loc, id=0, label="entry")
    block.terminator = ir.SubroutineReturn(result=results, source_location=loc)
    sub.body = [block]


def _default_value(ir_type: IRType, loc: object) -> ir.Value:
    avm_type = ir_type.maybe_avm_type
    if avm_type == AVMType.uint64:
        return ir.UInt64Constant(value=0, ir_type=ir_type, source_location=loc)  # type: ignore[arg-type]
    if avm_type == AVMType.bytes:
        num_bytes = ir_type.num_bytes if isinstance(ir_type, SizedBytesType) else 0
        return ir.BytesConstant(
            value=b"\x00" * num_bytes,
            encoding=AVMBytesEncoding.base16,
            ir_type=ir_type,
            source_location=loc,  # type: ignore[arg-type]
        )
    return ir.Undefined(ir_type=ir_type, source_location=loc)  # type: ignore[arg-type]


# --- AWST detection + grafting (relay path) ---


def detect_config(awst: AWST) -> UrosChunks:
    """Detect a kwarg-driven uros config in the AWST: a Contract with ``splitter="uros"`` plus
    per-method ``@arc4.abimethod(chunk="...")`` markers.

    Returns ordered ``(chunk_name, method_names)`` pairs (first-seen order), or ``()`` if no
    contract opted in. Errors if a marked contract has an ``abimethod`` without ``chunk=``."""
    from puya.awst import nodes as awst_nodes

    targets = [
        n for n in awst if isinstance(n, awst_nodes.Contract) and n.splitter == SPLITTER_KEY
    ]
    if not targets:
        return ()
    if len(targets) > 1:
        raise CodeError(
            f"multiple contracts marked with splitter={SPLITTER_KEY!r} is not supported"
        )
    target = targets[0]
    chunks: dict[str, list[str]] = {}
    for m in target.methods:
        cfg = m.arc4_method_config
        if not isinstance(cfg, awst_nodes.ARC4ABIMethodConfig):
            continue
        # Unannotated ABI methods — including compiler-synthesised ones the user
        # can't annotate, e.g. the SimpleSplitter's `__delegate_update` — default
        # to the `shell` chunk. They stay real in the genesis shell and DCE trims
        # whatever each chunk doesn't reach, so no explicit marker is required.
        chunk = cfg.chunk if cfg.chunk is not None else "shell"
        if "+" in chunk:
            raise CodeError(
                f"{target.id}.{m.member_name}: chunk name {chunk!r} may not contain '+'"
                " ('+' is reserved as the chunk-name separator)"
            )
        chunks.setdefault(chunk, []).append(m.member_name)
    return tuple((name, tuple(methods)) for name, methods in chunks.items())


def inject_setup(
    awst: AWST,
    chunks: UrosChunks,
    compilation_set: typing.Mapping[ContractReference, Path],
) -> tuple[AWST, dict[ContractReference, Path]]:
    """Graft the uros infra (guard + setter + state) onto the user's `main` contract, inject
    the per-method "preceded by setup.prepare" guard into every split method, and append the
    `setup` helper so a single invocation emits the whole system. Returns the augmented AWST +
    the extra compilation-set entries to merge."""
    from puya.awst import nodes as awst_nodes
    from puya.awst.serialize import awst_from_json

    lib_nodes = awst_from_json(_EMBEDDED_LIB.read_text(encoding="utf8"))
    setup_node = next(n for n in lib_nodes if n.id == SETUP_CONTRACT_ID)
    infra_node = next(n for n in lib_nodes if n.id == INFRA_CONTRACT_ID)
    assert isinstance(infra_node, awst_nodes.Contract)

    requested = {m for _, methods in chunks for m in methods}
    out_dir: Path | None = None
    result = list(awst)
    for i, node in enumerate(result):
        if isinstance(node, awst_nodes.Contract) and {
            m.member_name for m in node.methods
        } & requested:
            out_dir = compilation_set.get(ContractReference(node.id))
            result[i] = _inject_guards(_graft_infra(node, infra_node), infra_node, requested)
            break

    result.append(setup_node)
    extra: dict[ContractReference, Path] = {}
    if out_dir is not None:
        extra[ContractReference(SETUP_CONTRACT_ID)] = out_dir
    return result, extra


def _graft_infra(target: AwstContract, infra: AwstContract) -> AwstContract:
    """Append the infra guard/setter methods (re-homed to `target`) and the `uros_setup` state
    onto the target. State access is keyed by bytes (not by contract ref), so rehoming is just
    rewriting each method's owning `cref`."""
    methods = tuple(
        attrs.evolve(m, cref=target.id)
        for m in infra.methods
        if m.member_name in INFRA_METHODS
    )
    grafted = attrs.evolve(
        target,
        methods=(*target.methods, *methods),
        app_state=(*target.app_state, *infra.app_state),
    )
    if grafted.state_totals is not None:
        grafted = attrs.evolve(
            grafted,
            state_totals=attrs.evolve(
                grafted.state_totals,
                global_uints=grafted.state_totals.global_uints + len(infra.app_state),
            ),
        )
    return grafted


def _inject_guards(
    target: AwstContract, infra: AwstContract, requested: set[str]
) -> AwstContract:
    """Prepend the guard template's `appl` arg + asserts to each split method, so every heavy
    method takes the preceding `setup.prepare` as a leading ABI transaction arg and verifies
    it. The arg/asserts reference the arg by name + uros_setup by key, so they splice
    verbatim."""
    from puya.awst import nodes as awst_nodes

    tmpl = next(m for m in infra.methods if m.member_name == GUARD_TEMPLATE_METHOD)
    guard_arg = tmpl.args[0]
    guard_stmts = tuple(
        s for s in tmpl.body.body if not isinstance(s, awst_nodes.ReturnStatement)
    )
    methods = tuple(
        attrs.evolve(
            m,
            args=(guard_arg, *m.args),
            body=attrs.evolve(m.body, body=(*guard_stmts, *m.body.body)),
        )
        if m.member_name in requested
        else m
        for m in target.methods
    )
    target = attrs.evolve(target, methods=methods)
    # The grafted guard adds a leading ABI transaction arg to each chunked method
    # so external clients auto-place setup.prepare. But an INTERNAL call (callsub)
    # can't supply an ABI transaction arg, so the now-2-arg signature breaks every
    # internal caller (e.g. `addAsset` -> `isUnderlyingListed`). Rewrite each
    # internal call to a chunked method to pass GroupTransactionReference(
    # GroupIndex - 1) — exactly the preceding setup.prepare the ABI router
    # resolves externally. GroupIndex is constant within a top-level txn, so an
    # internal call re-reads the same setup.prepare and the guard re-passes.
    # (Every chunk keeps all impls real and lets per-Contract DCE prune the
    # unreachable ones, so the callee's real body survives in whatever chunk
    # internally calls it; here we only fix the call signature.)
    return _rewrite_internal_calls(target, requested, guard_arg.wtype)


def _make_prep_ref(prep_wtype: object, loc: object) -> object:
    """Build `GroupTransactionReference(txn.GroupIndex - 1)` typed as the guard's
    transaction arg — the value the ABI router passes externally."""
    from puya.awst import nodes as awst_nodes
    from puya.awst import wtypes
    from puya.ir.arc4_router import _constant, _txn, _uint64_sub

    group_index = _txn("GroupIndex", wtypes.uint64_wtype, loc)
    index = _uint64_sub(group_index, _constant(1, loc), loc)
    return awst_nodes.GroupTransactionReference(
        index=index, wtype=prep_wtype, source_location=loc
    )


def _rewrite_internal_calls(
    target: AwstContract, requested: set[str], prep_wtype: object
) -> AwstContract:
    """Prepend a preceding-setup transaction arg to every internal call of a
    chunked method (see _inject_guards). Generic recursive rebuild over the AWST
    (frozen attrs nodes), intercepting SubroutineCallExpression targets."""
    import attrs as _attrs

    return _attrs.evolve(
        target,
        methods=tuple(_rewrite_node(m, requested, prep_wtype) for m in target.methods),
    )


def _rewrite_node(node: object, requested: set[str], prep_wtype: object) -> object:
    import attrs as _attrs

    from puya.awst import nodes as awst_nodes

    changes = {}
    for f in _attrs.fields(type(node)):
        v = getattr(node, f.name)
        nv = _rewrite_value(v, requested, prep_wtype)
        if nv is not v:
            changes[f.name] = nv
    if changes:
        node = _attrs.evolve(node, **changes)
    if (
        isinstance(node, awst_nodes.SubroutineCallExpression)
        and isinstance(
            node.target,
            (
                awst_nodes.InstanceMethodTarget,
                awst_nodes.InstanceSuperMethodTarget,
                awst_nodes.ContractMethodTarget,
            ),
        )
        and node.target.member_name in requested
    ):
        prep = awst_nodes.CallArg(
            name=None, value=_make_prep_ref(prep_wtype, node.source_location)
        )
        node = _attrs.evolve(node, args=(prep, *node.args))
    return node


def _rewrite_value(v: object, requested: set[str], prep_wtype: object) -> object:
    import attrs as _attrs
    from collections.abc import Mapping

    from puya.awst import nodes as awst_nodes

    if isinstance(v, awst_nodes.Node):
        return _rewrite_node(v, requested, prep_wtype)
    if isinstance(v, awst_nodes.CallArg):
        nv = _rewrite_value(v.value, requested, prep_wtype)
        return _attrs.evolve(v, value=nv) if nv is not v.value else v
    if isinstance(v, tuple):
        return tuple(_rewrite_value(x, requested, prep_wtype) for x in v)
    # Mapping fields (immutabledict): NewStruct.values, Switch.cases (Expression
    # keys), inner-txn field maps. Recurse keys AND values; the attrs converter
    # re-wraps the plain dict on evolve. Without this, calls nested in e.g. an
    # ARC-4 struct literal arg are missed (AAVE Hub's AssetConfig{...}).
    if isinstance(v, Mapping):
        return {
            _rewrite_value(k, requested, prep_wtype): _rewrite_value(
                val, requested, prep_wtype
            )
            for k, val in v.items()
        }
    return v


# --- IR-level dispatch (after awst_to_ir) ---


def apply(
    context: CompileContext,
    ir_artifacts: list[ir.ModuleArtifact],
    chunks: UrosChunks,
) -> tuple[list[ir.ModuleArtifact], CompileContext, UrosChunks]:
    requested = {m for _, methods in chunks for m in methods}
    targets = [
        a
        for a in ir_artifacts
        if isinstance(a, ir.Contract) and (abi_method_names(a) & requested)
    ]
    if not targets:
        raise CodeError(
            "uros splitter: no compiled contract contains the requested method(s):"
            f" {', '.join(sorted(requested))}"
        )
    if len(targets) > 1:
        raise CodeError("uros splitter: requested methods span multiple contracts")
    target = targets[0]
    out_dir = context.compilation_set.get(target.metadata.ref)

    # resolve `chunk=` hints into final chunks: each hint chunk stays its own chunk, except
    # hint-chunks whose ABI methods call each other are force-merged (only one chunk is live at a
    # time, so a callee can't be a stub). The resolved grouping (+ merged names) is returned for
    # the manifest. Chunk sizing is the author's responsibility; the assembler enforces 8 KB.
    resolved = _resolve_chunks(target, chunks)

    keep_real = set(INFRA_METHODS) & abi_method_names(target)
    groups = [list(methods) for _, methods in resolved]
    main_shell, chunk_contracts = split_contract(target, groups, keep_real=keep_real)

    new_ir: list[ir.ModuleArtifact] = [a for a in ir_artifacts if a is not target]
    new_ir.append(main_shell)

    new_compilation_set = dict(context.compilation_set)
    for (name, _methods), c in zip(resolved, chunk_contracts, strict=True):
        suffix = f"__chunk_{name}"
        chunk_ref = ContractReference(f"{target.metadata.ref}{suffix}")
        c.metadata = attrs.evolve(
            c.metadata, ref=chunk_ref, name=f"{target.metadata.name}{suffix}"
        )
        if out_dir is not None:
            new_compilation_set[chunk_ref] = out_dir
        new_ir.append(c)

    context.compilation_set = new_compilation_set
    return new_ir, context, resolved


def _resolve_chunks(contract: ir.Contract, chunks: UrosChunks) -> UrosChunks:
    """Each `chunk=` hint stays its own chunk. Cross-chunk internal calls used to require
    force-merging call-connected hint-chunks (a callee can't be a stub); that is no longer needed
    — split_contract keeps every impl real per chunk and lets per-Contract DCE prune the
    unreachable ones, so a chunk that internally calls another chunk's ABI method just keeps that
    impl. Only validate the chunk names fit the 64-byte box-key limit."""
    for name, _ in chunks:
        if len(name.encode()) > 64:
            raise CodeError(
                f"uros splitter: chunk name {name!r} exceeds the 64-byte box-key limit;"
                " use fewer / coarser chunk= hints"
            )
    return chunks


def write_manifest(
    context: CompileContext,
    compiled_artifacts: list[CompilationArtifact],
    chunks: UrosChunks,
) -> None:
    """Emit `deploy.uros.json` — only the one fact the deploy can't get from the standard puya
    artifacts: the resolved method -> chunk mapping, plus the main/setup contract names
    so the deploy can locate those artifacts. Bytecode, schema and page count are read from the
    normal `<name>.approval.bin` / `<name>.arc56.json` outputs by the deploy."""
    import json

    from puya.artifact_metadata import ARC4ABIMethod
    from puya.utils import method_selector_hash

    chunk_of_method: dict[str, str] = {
        method: name for name, methods in chunks for method in methods
    }
    suffixes = tuple(f"__chunk_{name}" for name, _ in chunks)
    by_name = {a.metadata.name: a for a in compiled_artifacts if isinstance(a, CompiledContract)}
    setup = by_name.get(SETUP_CONTRACT_NAME)
    for name, app in by_name.items():
        if name == SETUP_CONTRACT_NAME:
            continue
        if any(by_name.get(f"{name}{s}") is None for s in suffixes):
            continue
        out_dir = context.compilation_set.get(app.id)
        if out_dir is None:
            continue
        manifest = {
            "main_contract": name,
            "setup_contract": SETUP_CONTRACT_NAME if setup is not None else None,
            "methods": [
                {
                    "name": m.name,
                    "selector": "0x" + method_selector_hash(m.signature).hex(),
                    "chunk": chunk_of_method[m.name],
                }
                for m in app.metadata.arc4_methods
                if isinstance(m, ARC4ABIMethod) and m.name in chunk_of_method
            ],
        }
        out_path = out_dir / "deploy.uros.json"
        logger.info(f"Writing {make_path_relative_to_cwd(out_path)}")
        out_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
